
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springboot-vue?characterEncoding=UTF-8&useUnicode=true&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: root
  redis:
    host: 127.0.0.1
    port: 6379