server:
  port: 12000
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  config-location: classpath:mybatis/configuration.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#  type-aliases-package: com.example.demo.entity

spring:
  # freemarker
  freemarker:
    enabled: true
    cache: false
    allow-request-override: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    request-context-attribute: requestContext
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: true
    suffix: .ftl
    template-loader-path: classpath:/views/
    settings.template_update_delay: 0
    settings.default_encoding: UTF-8
    settings.datetime_format: yyyy-MM-dd HH:mm:ss
    settings.classic_compatible: true
    settings.template_exception_handler: ignore
    settings.locale: zh_CN
    settings.number_format: 0.##########
    prefer-file-system-access: false
    #mvc
    mvc:
      view:
        prefix: classpath:/views/


logging:
  config: classpath:logback-spring.xml
  file:
    path: ./logs